#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "X36BM/9DBeK3"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

// === Home Row Mods ===
#define TAPPING_TERM 200
#define QUICK_TAP_TERM 150
#define PERMISSIVE_HOLD
